// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "addresses")
public class Address extends BaseEntity {
    private String fullName;
    private String phone;
    private String line1;
    private String line2;
    private String street;
    private String city;
    private String state;
    private String pincode;
    private String country = "India";
    private String label;
    private String landmark;
    private String deliveryInstructions;

    /**
     * Soft-delete flag. Addresses referenced by orders must never be hard-deleted, so removal
     * flips this off instead; the row stays for the order history and for admin restoration.
     */
    private Boolean activeFlag = true;

    /**
     * GSTIN registered at this address.
     *
     * Held per address rather than per customer because registration is per state: a company
     * trading in three states holds three GSTINs, and which one applies depends on which of
     * their addresses the supply is billed to. One GSTIN on the customer record would put the
     * wrong state on the invoice for two of them.
     */
    @Column(length = 15)
    private String gstin;
    private Boolean isDefault = false;
    private Boolean isBilling = false;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"addresses", "orders", "cart", "password", "refreshToken"})
    private User user;

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getLine1() {
        return this.line1;
    }

    @java.lang.SuppressWarnings("all")
    public String getLine2() {
        return this.line2;
    }

    @java.lang.SuppressWarnings("all")
    public String getStreet() {
        return this.street;
    }

    @java.lang.SuppressWarnings("all")
    public String getCity() {
        return this.city;
    }

    @java.lang.SuppressWarnings("all")
    public String getState() {
        return this.state;
    }

    @java.lang.SuppressWarnings("all")
    public String getPincode() {
        return this.pincode;
    }

    @java.lang.SuppressWarnings("all")
    public String getCountry() {
        return this.country;
    }

    @java.lang.SuppressWarnings("all")
    public String getLabel() {
        return this.label;
    }

    @java.lang.SuppressWarnings("all")
    public String getLandmark() {
        return this.landmark;
    }

    @java.lang.SuppressWarnings("all")
    public String getDeliveryInstructions() {
        return this.deliveryInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsDefault() {
        return this.isDefault;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getActiveFlag() {
        return this.activeFlag;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsBilling() {
        return this.isBilling;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setLine1(final String line1) {
        this.line1 = line1;
    }

    @java.lang.SuppressWarnings("all")
    public void setLine2(final String line2) {
        this.line2 = line2;
    }

    @java.lang.SuppressWarnings("all")
    public void setStreet(final String street) {
        this.street = street;
    }

    @java.lang.SuppressWarnings("all")
    public void setCity(final String city) {
        this.city = city;
    }

    @java.lang.SuppressWarnings("all")
    public void setState(final String state) {
        this.state = state;
    }

    @java.lang.SuppressWarnings("all")
    public void setPincode(final String pincode) {
        this.pincode = pincode;
    }

    @java.lang.SuppressWarnings("all")
    public void setCountry(final String country) {
        this.country = country;
    }

    @java.lang.SuppressWarnings("all")
    public void setLabel(final String label) {
        this.label = label;
    }

    @java.lang.SuppressWarnings("all")
    public void setLandmark(final String landmark) {
        this.landmark = landmark;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryInstructions(final String deliveryInstructions) {
        this.deliveryInstructions = deliveryInstructions;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsDefault(final Boolean isDefault) {
        this.isDefault = isDefault;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveFlag(final Boolean activeFlag) {
        this.activeFlag = activeFlag;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsBilling(final Boolean isBilling) {
        this.isBilling = isBilling;
    }

    @JsonIgnoreProperties({"addresses", "orders", "cart", "password", "refreshToken"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }
    public String getGstin() { return gstin; }
    public void setGstin(String gstin) { this.gstin = gstin; }
}
