// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "banners")
public class Banner extends BaseEntity {
    private String title;
    private String subtitle;
    @Column(columnDefinition = "TEXT")
    private String imageUrl;
    private String link;
    private String position;
    private Integer sortOrder;
    private boolean active = true;

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubtitle() {
        return this.subtitle;
    }

    @java.lang.SuppressWarnings("all")
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getLink() {
        return this.link;
    }

    @java.lang.SuppressWarnings("all")
    public String getPosition() {
        return this.position;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubtitle(final String subtitle) {
        this.subtitle = subtitle;
    }

    @java.lang.SuppressWarnings("all")
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setLink(final String link) {
        this.link = link;
    }

    @java.lang.SuppressWarnings("all")
    public void setPosition(final String position) {
        this.position = position;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }
}
