// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "carts")
public class Cart extends BaseEntity {
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties("cart")
    private User user;
    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @JsonIgnoreProperties("cart")
    private List<CartItem> items = new ArrayList<>();
    private int totalItems = 0;
    private double totalPrice = 0.0;

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public List<CartItem> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalItems() {
        return this.totalItems;
    }

    @java.lang.SuppressWarnings("all")
    public double getTotalPrice() {
        return this.totalPrice;
    }

    @JsonIgnoreProperties("cart")
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @JsonIgnoreProperties("cart")
    @java.lang.SuppressWarnings("all")
    public void setItems(final List<CartItem> items) {
        this.items = items;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalItems(final int totalItems) {
        this.totalItems = totalItems;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPrice(final double totalPrice) {
        this.totalPrice = totalPrice;
    }
}
