// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "coupons")
public class Coupon extends BaseEntity {
    @Column(unique = true)
    private String code;
    private String type;
    private Double value;
    private Double minOrderAmount;
    private Integer maxUses;
    private Integer usedCount = 0;
    private Double maxDiscountAmount;
    private LocalDateTime validFrom;
    private LocalDateTime validUntil;
    private boolean active = true;
    private String appliesTo;
    private Long appliesToId;
    private boolean freeShipping = false;

    @java.lang.SuppressWarnings("all")
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public Double getValue() {
        return this.value;
    }

    @java.lang.SuppressWarnings("all")
    public Double getMinOrderAmount() {
        return this.minOrderAmount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getMaxUses() {
        return this.maxUses;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getUsedCount() {
        return this.usedCount;
    }

    @java.lang.SuppressWarnings("all")
    public Double getMaxDiscountAmount() {
        return this.maxDiscountAmount;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getValidFrom() {
        return this.validFrom;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getValidUntil() {
        return this.validUntil;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getAppliesTo() {
        return this.appliesTo;
    }

    @java.lang.SuppressWarnings("all")
    public Long getAppliesToId() {
        return this.appliesToId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isFreeShipping() {
        return this.freeShipping;
    }

    @java.lang.SuppressWarnings("all")
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setValue(final Double value) {
        this.value = value;
    }

    @java.lang.SuppressWarnings("all")
    public void setMinOrderAmount(final Double minOrderAmount) {
        this.minOrderAmount = minOrderAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setMaxUses(final Integer maxUses) {
        this.maxUses = maxUses;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsedCount(final Integer usedCount) {
        this.usedCount = usedCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setMaxDiscountAmount(final Double maxDiscountAmount) {
        this.maxDiscountAmount = maxDiscountAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setValidFrom(final LocalDateTime validFrom) {
        this.validFrom = validFrom;
    }

    @java.lang.SuppressWarnings("all")
    public void setValidUntil(final LocalDateTime validUntil) {
        this.validUntil = validUntil;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppliesTo(final String appliesTo) {
        this.appliesTo = appliesTo;
    }

    @java.lang.SuppressWarnings("all")
    public void setAppliesToId(final Long appliesToId) {
        this.appliesToId = appliesToId;
    }

    @java.lang.SuppressWarnings("all")
    public void setFreeShipping(final boolean freeShipping) {
        this.freeShipping = freeShipping;
    }
}
