// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "email_otps")
public class EmailOtp extends BaseEntity {
    @Column(nullable = false)
    private String email;
    @Column(nullable = false)
    private String otp;
    private LocalDateTime expiresAt;
    private boolean used = false;
    private LocalDateTime lastRequestedAt;
    private Integer verifyAttempts = 0;
    private String purpose = "PASSWORD_RESET";

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getOtp() {
        return this.otp;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isUsed() {
        return this.used;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setOtp(final String otp) {
        this.otp = otp;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiresAt(final LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsed(final boolean used) {
        this.used = used;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastRequestedAt() {
        return this.lastRequestedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastRequestedAt(final LocalDateTime lastRequestedAt) {
        this.lastRequestedAt = lastRequestedAt;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getVerifyAttempts() {
        return this.verifyAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public void setVerifyAttempts(final Integer verifyAttempts) {
        this.verifyAttempts = verifyAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public String getPurpose() {
        return this.purpose;
    }

    @java.lang.SuppressWarnings("all")
    public void setPurpose(final String purpose) {
        this.purpose = purpose;
    }
}
