// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "faqs")
public class Faq extends BaseEntity {
    private String question;
    @Column(columnDefinition = "TEXT")
    private String answer;
    private String category;
    private Integer sortOrder;
    private boolean active = true;

    @java.lang.SuppressWarnings("all")
    public String getQuestion() {
        return this.question;
    }

    @java.lang.SuppressWarnings("all")
    public String getAnswer() {
        return this.answer;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuestion(final String question) {
        this.question = question;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnswer(final String answer) {
        this.answer = answer;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }
}
