// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

@Entity
@Table(name = "impersonation_sessions")
public class ImpersonationSession {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Long impersonatorId;
    private Long targetUserId;
    private String reason;
    private String targetRole;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private boolean active;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getImpersonatorId() {
        return this.impersonatorId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getTargetUserId() {
        return this.targetUserId;
    }

    @java.lang.SuppressWarnings("all")
    public String getReason() {
        return this.reason;
    }

    @java.lang.SuppressWarnings("all")
    public String getTargetRole() {
        return this.targetRole;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setImpersonatorId(final Long impersonatorId) {
        this.impersonatorId = impersonatorId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTargetUserId(final Long targetUserId) {
        this.targetUserId = targetUserId;
    }

    @java.lang.SuppressWarnings("all")
    public void setReason(final String reason) {
        this.reason = reason;
    }

    @java.lang.SuppressWarnings("all")
    public void setTargetRole(final String targetRole) {
        this.targetRole = targetRole;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartTime(final LocalDateTime startTime) {
        this.startTime = startTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setEndTime(final LocalDateTime endTime) {
        this.endTime = endTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }
}
