// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "inventory")
public class Inventory extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    @JsonIgnoreProperties({"images", "variants", "reviews", "questions", "discounts"})
    private Product product;
    private Integer stock;

    @java.lang.SuppressWarnings("all")
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStock() {
        return this.stock;
    }

    @JsonIgnoreProperties({"images", "variants", "reviews", "questions", "discounts"})
    @java.lang.SuppressWarnings("all")
    public void setProduct(final Product product) {
        this.product = product;
    }

    @java.lang.SuppressWarnings("all")
    public void setStock(final Integer stock) {
        this.stock = stock;
    }
}
