// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.*;

@Entity
@Table(name = "loyalty_rules")
public class LoyaltyRule extends BaseEntity {
    private String name;
    private String description;
    private Double pointsPerUnit = 1.0;
    private Double minimumOrderAmount = 0.0;
    private boolean active = true;

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPointsPerUnit() {
        return this.pointsPerUnit;
    }

    @java.lang.SuppressWarnings("all")
    public Double getMinimumOrderAmount() {
        return this.minimumOrderAmount;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setPointsPerUnit(final Double pointsPerUnit) {
        this.pointsPerUnit = pointsPerUnit;
    }

    @java.lang.SuppressWarnings("all")
    public void setMinimumOrderAmount(final Double minimumOrderAmount) {
        this.minimumOrderAmount = minimumOrderAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }
}
