// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "orders")
public class Order extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"orders", "cart", "addresses", "password", "refreshToken", "role", "email", "phone"})
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id")
    private Address address;
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties({"order", "product"})
    private List<OrderItem> items = new ArrayList<>();
    private double totalAmount;
    private boolean paid = false;
    private String status = "PLACED";
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("order")
    private List<OrderTimeline> timeline = new ArrayList<>();
    private String paymentMethod;
    private String region;
    private String trackingNumber;
    private String courier;
    private LocalDateTime shippedAt;
    private LocalDateTime deliveredAt;
    private Double subTotal;
    private Double tax;
    private Double deliveryCharge;
    private Long sellerId;

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public Address getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public List<OrderItem> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    public double getTotalAmount() {
        return this.totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isPaid() {
        return this.paid;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public List<OrderTimeline> getTimeline() {
        return this.timeline;
    }

    @java.lang.SuppressWarnings("all")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    public String getTrackingNumber() {
        return this.trackingNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getCourier() {
        return this.courier;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getShippedAt() {
        return this.shippedAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getDeliveredAt() {
        return this.deliveredAt;
    }

    @java.lang.SuppressWarnings("all")
    public Double getSubTotal() {
        return this.subTotal;
    }

    @java.lang.SuppressWarnings("all")
    public Double getTax() {
        return this.tax;
    }

    @java.lang.SuppressWarnings("all")
    public Double getDeliveryCharge() {
        return this.deliveryCharge;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSellerId() {
        return this.sellerId;
    }

    @JsonIgnoreProperties({"orders", "cart", "addresses", "password", "refreshToken", "role", "email", "phone"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final Address address) {
        this.address = address;
    }

    @JsonIgnoreProperties({"order", "product"})
    @java.lang.SuppressWarnings("all")
    public void setItems(final List<OrderItem> items) {
        this.items = items;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalAmount(final double totalAmount) {
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaid(final boolean paid) {
        this.paid = paid;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @JsonIgnoreProperties("order")
    @java.lang.SuppressWarnings("all")
    public void setTimeline(final List<OrderTimeline> timeline) {
        this.timeline = timeline;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaymentMethod(final String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    public void setRegion(final String region) {
        this.region = region;
    }

    @java.lang.SuppressWarnings("all")
    public void setTrackingNumber(final String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourier(final String courier) {
        this.courier = courier;
    }

    @java.lang.SuppressWarnings("all")
    public void setShippedAt(final LocalDateTime shippedAt) {
        this.shippedAt = shippedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveredAt(final LocalDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubTotal(final Double subTotal) {
        this.subTotal = subTotal;
    }

    @java.lang.SuppressWarnings("all")
    public void setTax(final Double tax) {
        this.tax = tax;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryCharge(final Double deliveryCharge) {
        this.deliveryCharge = deliveryCharge;
    }

    @java.lang.SuppressWarnings("all")
    public void setSellerId(final Long sellerId) {
        this.sellerId = sellerId;
    }
}
