// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "page_content")
public class PageContent extends BaseEntity {
    private String slug;
    private String title;
    @Column(columnDefinition = "TEXT")
    private String content;
    private String type;
    private boolean active = true;
    private String metaTitle;
    @Column(columnDefinition = "TEXT")
    private String metaDescription;

    @java.lang.SuppressWarnings("all")
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getMetaTitle() {
        return this.metaTitle;
    }

    @java.lang.SuppressWarnings("all")
    public String getMetaDescription() {
        return this.metaDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetaTitle(final String metaTitle) {
        this.metaTitle = metaTitle;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetaDescription(final String metaDescription) {
        this.metaDescription = metaDescription;
    }
}
