// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
public class Payment extends BaseEntity {
    private String razorpayOrderId;
    private String razorpayPaymentId;
    private String razorpaySignature;
    private Double amount;
    private String currency;
    private String status;
    private Long orderId;
    private String receipt;
    private LocalDateTime paidAt;

    @java.lang.SuppressWarnings("all")
    public String getRazorpayOrderId() {
        return this.razorpayOrderId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRazorpayPaymentId() {
        return this.razorpayPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRazorpaySignature() {
        return this.razorpaySignature;
    }

    @java.lang.SuppressWarnings("all")
    public Double getAmount() {
        return this.amount;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrency() {
        return this.currency;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Long getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    public String getReceipt() {
        return this.receipt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getPaidAt() {
        return this.paidAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setRazorpayOrderId(final String razorpayOrderId) {
        this.razorpayOrderId = razorpayOrderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRazorpayPaymentId(final String razorpayPaymentId) {
        this.razorpayPaymentId = razorpayPaymentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRazorpaySignature(final String razorpaySignature) {
        this.razorpaySignature = razorpaySignature;
    }

    @java.lang.SuppressWarnings("all")
    public void setAmount(final Double amount) {
        this.amount = amount;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderId(final Long orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setReceipt(final String receipt) {
        this.receipt = receipt;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaidAt(final LocalDateTime paidAt) {
        this.paidAt = paidAt;
    }
}
