// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "platform_settings")
public class PlatformSetting {
    @Id
    private String settingKey;
    @Column(columnDefinition = "TEXT")
    private String settingValue;
    private String description;
    private String category;

    @java.lang.SuppressWarnings("all")
    public String getSettingKey() {
        return this.settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public String getSettingValue() {
        return this.settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingKey(final String settingKey) {
        this.settingKey = settingKey;
    }

    @java.lang.SuppressWarnings("all")
    public void setSettingValue(final String settingValue) {
        this.settingValue = settingValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }
}
