// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "product_answers")
public class ProductAnswer extends BaseEntity {
    @Column(columnDefinition = "TEXT")
    private String answer;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question_id")
    @JsonIgnoreProperties("answers")
    private ProductQuestion question;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"password", "refreshToken"})
    private User user;

    @java.lang.SuppressWarnings("all")
    public String getAnswer() {
        return this.answer;
    }

    @java.lang.SuppressWarnings("all")
    public ProductQuestion getQuestion() {
        return this.question;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnswer(final String answer) {
        this.answer = answer;
    }

    @JsonIgnoreProperties("answers")
    @java.lang.SuppressWarnings("all")
    public void setQuestion(final ProductQuestion question) {
        this.question = question;
    }

    @JsonIgnoreProperties({"password", "refreshToken"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }
}
