// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "product_images")
public class ProductImage extends BaseEntity {
    @Column(nullable = false)
    private String url;
    private String thumbUrl;
    private String previewUrl;
    private String zoomUrl;
    private String originalUrl;
    private boolean main = false;
    private Integer sortOrder = 0;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    @JsonIgnoreProperties({"images", "variants", "reviews", "questions", "discounts"})
    private Product product;

    public void setProductId(Long productId) {
        if (this.product == null) {
            this.product = new Product();
        }
        this.product.setId(productId);
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSortOrder() {
        return this.sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public String getThumbUrl() {
        return this.thumbUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isMain() {
        return this.main;
    }

    @java.lang.SuppressWarnings("all")
    public void setSortOrder(final Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setThumbUrl(final String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setMain(final boolean main) {
        this.main = main;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreviewUrl() {
        return this.previewUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getZoomUrl() {
        return this.zoomUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getOriginalUrl() {
        return this.originalUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreviewUrl(final String previewUrl) {
        this.previewUrl = previewUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setZoomUrl(final String zoomUrl) {
        this.zoomUrl = zoomUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setOriginalUrl(final String originalUrl) {
        this.originalUrl = originalUrl;
    }

    @JsonIgnoreProperties({"images", "variants", "reviews", "questions", "discounts"})
    @java.lang.SuppressWarnings("all")
    public void setProduct(final Product product) {
        this.product = product;
    }
}
