// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "product_questions")
public class ProductQuestion extends BaseEntity {
    @Column(columnDefinition = "TEXT")
    private String question;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    @JsonIgnoreProperties({"questions", "reviews", "images", "variants", "discounts"})
    private Product product;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"password", "refreshToken", "role", "email", "phone", "orders", "cart", "addresses", "active", "status"})
    private User user;
    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("question")
    private List<ProductAnswer> answers = new ArrayList<>();

    @java.lang.SuppressWarnings("all")
    public String getQuestion() {
        return this.question;
    }

    @java.lang.SuppressWarnings("all")
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductAnswer> getAnswers() {
        return this.answers;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuestion(final String question) {
        this.question = question;
    }

    @JsonIgnoreProperties({"questions", "reviews", "images", "variants", "discounts"})
    @java.lang.SuppressWarnings("all")
    public void setProduct(final Product product) {
        this.product = product;
    }

    @JsonIgnoreProperties({"password", "refreshToken", "role", "email", "phone", "orders", "cart", "addresses", "active", "status"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @JsonIgnoreProperties("question")
    @java.lang.SuppressWarnings("all")
    public void setAnswers(final List<ProductAnswer> answers) {
        this.answers = answers;
    }
}
