// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "product_variants")
public class ProductVariant extends BaseEntity {
    private String variantType;
    private String variantValue;
    private Double price;
    private Integer stock = 0;
    private String sku;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    @JsonIgnoreProperties({"variants", "images", "reviews", "questions", "discounts"})
    private Product product;

    @java.lang.SuppressWarnings("all")
    public String getVariantType() {
        return this.variantType;
    }

    @java.lang.SuppressWarnings("all")
    public String getVariantValue() {
        return this.variantValue;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStock() {
        return this.stock;
    }

    @java.lang.SuppressWarnings("all")
    public String getSku() {
        return this.sku;
    }

    @java.lang.SuppressWarnings("all")
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    public void setVariantType(final String variantType) {
        this.variantType = variantType;
    }

    @java.lang.SuppressWarnings("all")
    public void setVariantValue(final String variantValue) {
        this.variantValue = variantValue;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    public void setStock(final Integer stock) {
        this.stock = stock;
    }

    @java.lang.SuppressWarnings("all")
    public void setSku(final String sku) {
        this.sku = sku;
    }

    @JsonIgnoreProperties({"variants", "images", "reviews", "questions", "discounts"})
    @java.lang.SuppressWarnings("all")
    public void setProduct(final Product product) {
        this.product = product;
    }
}
