// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "product_reviews")
public class ProductReview extends BaseEntity {
    private int rating;
    private boolean approved;
    @Column(columnDefinition = "TEXT")
    private String comment;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    @JsonIgnoreProperties({"reviews", "images", "variants", "questions", "discounts"})
    private Product product;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    @JsonIgnoreProperties({"password", "refreshToken", "role", "email", "phone", "orders", "cart", "addresses", "active", "status"})
    private User user;

    @java.lang.SuppressWarnings("all")
    public int getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isApproved() {
        return this.approved;
    }

    @java.lang.SuppressWarnings("all")
    public String getComment() {
        return this.comment;
    }

    @java.lang.SuppressWarnings("all")
    public Product getProduct() {
        return this.product;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public void setRating(final int rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    public void setApproved(final boolean approved) {
        this.approved = approved;
    }

    @java.lang.SuppressWarnings("all")
    public void setComment(final String comment) {
        this.comment = comment;
    }

    @JsonIgnoreProperties({"reviews", "images", "variants", "questions", "discounts"})
    @java.lang.SuppressWarnings("all")
    public void setProduct(final Product product) {
        this.product = product;
    }

    @JsonIgnoreProperties({"password", "refreshToken", "role", "email", "phone", "orders", "cart", "addresses", "active", "status"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }
}
