// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "products")
public class Product extends BaseEntity {
    @Column(unique = true, length = 20)
    private String productCode;
    @Column(nullable = false)
    private String name;
    @Column(columnDefinition = "TEXT")
    private String description;
    private Double price;
    private Integer stock;
    private boolean active = true;
    private String sku;
    private String approvalStatus = "approved";
    private String brand;
    private String manufacturer;
    private String modelNumber;
    private String barcode;
    private String color;
    private String size;
    private String material;
    private String subCategory;
    private Long collectionId;
    @ElementCollection
    private List<String> tags = new ArrayList<>();
    private String videoUrl;
    @Column(columnDefinition = "TEXT")
    private String pdfManualUrl;
    private Double offerPrice;
    private Double gstPercentage;
    private Double wholesalePrice;
    private Integer wholesaleMinQty;
    private Boolean featured = false;
    private Boolean trending = false;
    private Boolean bestSeller = false;
    private Boolean newArrival = false;
    private Integer qualityScore;
    private Integer missingFields;
    private String hsnCode;
    private String countryOfOrigin;
    private String metaTitle;
    @Column(columnDefinition = "TEXT")
    private String metaDescription;
    private String metaKeywords;
    private String slug;
    @Column(columnDefinition = "TEXT")
    private String shortDescription;
    @Column(columnDefinition = "TEXT")
    private String technicalSpecs;
    private String warranty;
    @Column(columnDefinition = "TEXT")
    private String returnPolicy;
    private Double weight;
    private String dimensions;
    private Double packageWeight;
    private String packageDimensions;
    private String shippingClass;
    private Integer deliveryDays;
    private Boolean codAvailable = true;
    private Boolean returnEligible = true;
    private Integer returnWindow = 7;
    private Long sellerId;
    private String productStatus = "published";
    private String channel = "ALL";
    private Long viewCount = 0L;
    @ElementCollection
    private List<String> badges = new ArrayList<>();
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    @JsonIgnoreProperties("products")
    private Category category;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "brand_id")
    @JsonIgnoreProperties("products")
    private Brand productBrand;
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("product")
    private List<ProductImage> images = new ArrayList<>();
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("product")
    private List<ProductVariant> variants = new ArrayList<>();
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("product")
    private List<ProductReview> reviews = new ArrayList<>();
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("product")
    private List<ProductQuestion> questions = new ArrayList<>();
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("product")
    private List<Discount> discounts = new ArrayList<>();

    @PrePersist
    public void generateCode() {
        if (this.productCode == null || this.productCode.isEmpty()) {
            this.productCode = java.util.UUID.randomUUID().toString().replace("-", "").substring(0, 10).toUpperCase();
        }
        if (this.approvalStatus == null) this.approvalStatus = "approved";
    }

    @java.lang.SuppressWarnings("all")
    public String getProductCode() {
        return this.productCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStock() {
        return this.stock;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getSku() {
        return this.sku;
    }

    @java.lang.SuppressWarnings("all")
    public String getApprovalStatus() {
        return this.approvalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getBrand() {
        return this.brand;
    }

    @java.lang.SuppressWarnings("all")
    public String getManufacturer() {
        return this.manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public String getModelNumber() {
        return this.modelNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getBarcode() {
        return this.barcode;
    }

    @java.lang.SuppressWarnings("all")
    public String getColor() {
        return this.color;
    }

    @java.lang.SuppressWarnings("all")
    public String getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    public String getMaterial() {
        return this.material;
    }

    @java.lang.SuppressWarnings("all")
    public String getHsnCode() {
        return this.hsnCode;
    }

    @java.lang.SuppressWarnings("all")
    public String getCountryOfOrigin() {
        return this.countryOfOrigin;
    }

    @java.lang.SuppressWarnings("all")
    public String getMetaTitle() {
        return this.metaTitle;
    }

    @java.lang.SuppressWarnings("all")
    public String getMetaDescription() {
        return this.metaDescription;
    }

    @java.lang.SuppressWarnings("all")
    public String getMetaKeywords() {
        return this.metaKeywords;
    }

    @java.lang.SuppressWarnings("all")
    public String getSlug() {
        return this.slug;
    }

    @java.lang.SuppressWarnings("all")
    public String getShortDescription() {
        return this.shortDescription;
    }

    @java.lang.SuppressWarnings("all")
    public String getTechnicalSpecs() {
        return this.technicalSpecs;
    }

    @java.lang.SuppressWarnings("all")
    public String getWarranty() {
        return this.warranty;
    }

    @java.lang.SuppressWarnings("all")
    public String getReturnPolicy() {
        return this.returnPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public Double getWeight() {
        return this.weight;
    }

    @java.lang.SuppressWarnings("all")
    public String getDimensions() {
        return this.dimensions;
    }

    @java.lang.SuppressWarnings("all")
    public Double getPackageWeight() {
        return this.packageWeight;
    }

    @java.lang.SuppressWarnings("all")
    public String getPackageDimensions() {
        return this.packageDimensions;
    }

    @java.lang.SuppressWarnings("all")
    public String getShippingClass() {
        return this.shippingClass;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getDeliveryDays() {
        return this.deliveryDays;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCodAvailable() {
        return this.codAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getReturnEligible() {
        return this.returnEligible;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getReturnWindow() {
        return this.returnWindow;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSellerId() {
        return this.sellerId;
    }

    @java.lang.SuppressWarnings("all")
    public String getProductStatus() {
        return this.productStatus;
    }

    @java.lang.SuppressWarnings("all")
    public Long getViewCount() {
        return this.viewCount;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getBadges() {
        return this.badges;
    }

    @java.lang.SuppressWarnings("all")
    public Category getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public Brand getProductBrand() {
        return this.productBrand;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductImage> getImages() {
        return this.images;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductVariant> getVariants() {
        return this.variants;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductReview> getReviews() {
        return this.reviews;
    }

    @java.lang.SuppressWarnings("all")
    public List<ProductQuestion> getQuestions() {
        return this.questions;
    }

    @java.lang.SuppressWarnings("all")
    public List<Discount> getDiscounts() {
        return this.discounts;
    }

    @java.lang.SuppressWarnings("all")
    public void setProductCode(final String productCode) {
        this.productCode = productCode;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrice(final Double price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    public void setStock(final Integer stock) {
        this.stock = stock;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setSku(final String sku) {
        this.sku = sku;
    }

    @java.lang.SuppressWarnings("all")
    public void setApprovalStatus(final String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setBrand(final String brand) {
        this.brand = brand;
    }

    @java.lang.SuppressWarnings("all")
    public void setManufacturer(final String manufacturer) {
        this.manufacturer = manufacturer;
    }

    @java.lang.SuppressWarnings("all")
    public void setModelNumber(final String modelNumber) {
        this.modelNumber = modelNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setBarcode(final String barcode) {
        this.barcode = barcode;
    }

    @java.lang.SuppressWarnings("all")
    public void setColor(final String color) {
        this.color = color;
    }

    @java.lang.SuppressWarnings("all")
    public void setSize(final String size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    public void setMaterial(final String material) {
        this.material = material;
    }

    @java.lang.SuppressWarnings("all")
    public void setHsnCode(final String hsnCode) {
        this.hsnCode = hsnCode;
    }

    @java.lang.SuppressWarnings("all")
    public void setCountryOfOrigin(final String countryOfOrigin) {
        this.countryOfOrigin = countryOfOrigin;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetaTitle(final String metaTitle) {
        this.metaTitle = metaTitle;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetaDescription(final String metaDescription) {
        this.metaDescription = metaDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetaKeywords(final String metaKeywords) {
        this.metaKeywords = metaKeywords;
    }

    @java.lang.SuppressWarnings("all")
    public void setSlug(final String slug) {
        this.slug = slug;
    }

    @java.lang.SuppressWarnings("all")
    public void setShortDescription(final String shortDescription) {
        this.shortDescription = shortDescription;
    }

    @java.lang.SuppressWarnings("all")
    public void setTechnicalSpecs(final String technicalSpecs) {
        this.technicalSpecs = technicalSpecs;
    }

    @java.lang.SuppressWarnings("all")
    public void setWarranty(final String warranty) {
        this.warranty = warranty;
    }

    @java.lang.SuppressWarnings("all")
    public void setReturnPolicy(final String returnPolicy) {
        this.returnPolicy = returnPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeight(final Double weight) {
        this.weight = weight;
    }

    @java.lang.SuppressWarnings("all")
    public void setDimensions(final String dimensions) {
        this.dimensions = dimensions;
    }

    @java.lang.SuppressWarnings("all")
    public void setPackageWeight(final Double packageWeight) {
        this.packageWeight = packageWeight;
    }

    @java.lang.SuppressWarnings("all")
    public void setPackageDimensions(final String packageDimensions) {
        this.packageDimensions = packageDimensions;
    }

    @java.lang.SuppressWarnings("all")
    public void setShippingClass(final String shippingClass) {
        this.shippingClass = shippingClass;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryDays(final Integer deliveryDays) {
        this.deliveryDays = deliveryDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setCodAvailable(final Boolean codAvailable) {
        this.codAvailable = codAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public void setReturnEligible(final Boolean returnEligible) {
        this.returnEligible = returnEligible;
    }

    @java.lang.SuppressWarnings("all")
    public void setReturnWindow(final Integer returnWindow) {
        this.returnWindow = returnWindow;
    }

    @java.lang.SuppressWarnings("all")
    public void setSellerId(final Long sellerId) {
        this.sellerId = sellerId;
    }

    @java.lang.SuppressWarnings("all")
    public void setProductStatus(final String productStatus) {
        this.productStatus = productStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getChannel() { return this.channel; }

    @java.lang.SuppressWarnings("all")
    public void setChannel(final String channel) { this.channel = channel; }

    @java.lang.SuppressWarnings("all")
    public void setViewCount(final Long viewCount) {
        this.viewCount = viewCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setBadges(final List<String> badges) {
        this.badges = badges;
    }

    @JsonIgnoreProperties("products")
    @java.lang.SuppressWarnings("all")
    public void setCategory(final Category category) {
        this.category = category;
    }

    @JsonIgnoreProperties("products")
    @java.lang.SuppressWarnings("all")
    public void setProductBrand(final Brand productBrand) {
        this.productBrand = productBrand;
    }

    @JsonIgnoreProperties("product")
    @java.lang.SuppressWarnings("all")
    public void setImages(final List<ProductImage> images) {
        this.images = images;
    }

    @JsonIgnoreProperties("product")
    @java.lang.SuppressWarnings("all")
    public void setVariants(final List<ProductVariant> variants) {
        this.variants = variants;
    }

    @JsonIgnoreProperties("product")
    @java.lang.SuppressWarnings("all")
    public void setReviews(final List<ProductReview> reviews) {
        this.reviews = reviews;
    }

    @JsonIgnoreProperties("product")
    @java.lang.SuppressWarnings("all")
    public void setQuestions(final List<ProductQuestion> questions) {
        this.questions = questions;
    }

    @JsonIgnoreProperties("product")
    @java.lang.SuppressWarnings("all")
    public void setDiscounts(final List<Discount> discounts) {
        this.discounts = discounts;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubCategory() { return this.subCategory; }

    @java.lang.SuppressWarnings("all")
    public void setSubCategory(final String subCategory) { this.subCategory = subCategory; }

    @java.lang.SuppressWarnings("all")
    public Long getCollectionId() { return this.collectionId; }

    @java.lang.SuppressWarnings("all")
    public void setCollectionId(final Long collectionId) { this.collectionId = collectionId; }

    @java.lang.SuppressWarnings("all")
    public List<String> getTags() { return this.tags; }

    @java.lang.SuppressWarnings("all")
    public void setTags(final List<String> tags) { this.tags = tags; }

    @java.lang.SuppressWarnings("all")
    public String getVideoUrl() { return this.videoUrl; }

    @java.lang.SuppressWarnings("all")
    public void setVideoUrl(final String videoUrl) { this.videoUrl = videoUrl; }

    @java.lang.SuppressWarnings("all")
    public String getPdfManualUrl() { return this.pdfManualUrl; }

    @java.lang.SuppressWarnings("all")
    public void setPdfManualUrl(final String pdfManualUrl) { this.pdfManualUrl = pdfManualUrl; }

    @java.lang.SuppressWarnings("all")
    public Double getOfferPrice() { return this.offerPrice; }

    @java.lang.SuppressWarnings("all")
    public void setOfferPrice(final Double offerPrice) { this.offerPrice = offerPrice; }

    @java.lang.SuppressWarnings("all")
    public Double getGstPercentage() { return this.gstPercentage; }

    @java.lang.SuppressWarnings("all")
    public void setGstPercentage(final Double gstPercentage) { this.gstPercentage = gstPercentage; }

    @java.lang.SuppressWarnings("all")
    public Double getWholesalePrice() { return this.wholesalePrice; }

    @java.lang.SuppressWarnings("all")
    public void setWholesalePrice(final Double wholesalePrice) { this.wholesalePrice = wholesalePrice; }

    @java.lang.SuppressWarnings("all")
    public Integer getWholesaleMinQty() { return this.wholesaleMinQty; }

    @java.lang.SuppressWarnings("all")
    public void setWholesaleMinQty(final Integer wholesaleMinQty) { this.wholesaleMinQty = wholesaleMinQty; }

    @java.lang.SuppressWarnings("all")
    public Boolean getFeatured() { return this.featured; }

    @java.lang.SuppressWarnings("all")
    public void setFeatured(final Boolean featured) { this.featured = featured; }

    @java.lang.SuppressWarnings("all")
    public Boolean getTrending() { return this.trending; }

    @java.lang.SuppressWarnings("all")
    public void setTrending(final Boolean trending) { this.trending = trending; }

    @java.lang.SuppressWarnings("all")
    public Boolean getBestSeller() { return this.bestSeller; }

    @java.lang.SuppressWarnings("all")
    public void setBestSeller(final Boolean bestSeller) { this.bestSeller = bestSeller; }

    @java.lang.SuppressWarnings("all")
    public Boolean getNewArrival() { return this.newArrival; }

    @java.lang.SuppressWarnings("all")
    public void setNewArrival(final Boolean newArrival) { this.newArrival = newArrival; }

    @java.lang.SuppressWarnings("all")
    public Integer getQualityScore() { return this.qualityScore; }

    @java.lang.SuppressWarnings("all")
    public void setQualityScore(final Integer qualityScore) { this.qualityScore = qualityScore; }

    @java.lang.SuppressWarnings("all")
    public Integer getMissingFields() { return this.missingFields; }

    @java.lang.SuppressWarnings("all")
    public void setMissingFields(final Integer missingFields) { this.missingFields = missingFields; }
}
