// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;

@Entity
@Table(name = "saved_payment_methods")
public class SavedPaymentMethod extends BaseEntity {
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @JsonIgnoreProperties({"password", "refreshToken", "orders", "cart", "addresses"})
    private User user;
    @Column(nullable = false)
    private String type;
    private String maskedNumber;
    private String expiry;
    private String cardholderName;
    private String upiId;
    private String bankName;
    private Boolean isDefault = false;

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getMaskedNumber() {
        return this.maskedNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getExpiry() {
        return this.expiry;
    }

    @java.lang.SuppressWarnings("all")
    public String getCardholderName() {
        return this.cardholderName;
    }

    @java.lang.SuppressWarnings("all")
    public String getUpiId() {
        return this.upiId;
    }

    @java.lang.SuppressWarnings("all")
    public String getBankName() {
        return this.bankName;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsDefault() {
        return this.isDefault;
    }

    @JsonIgnoreProperties({"password", "refreshToken", "orders", "cart", "addresses"})
    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setMaskedNumber(final String maskedNumber) {
        this.maskedNumber = maskedNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiry(final String expiry) {
        this.expiry = expiry;
    }

    @java.lang.SuppressWarnings("all")
    public void setCardholderName(final String cardholderName) {
        this.cardholderName = cardholderName;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpiId(final String upiId) {
        this.upiId = upiId;
    }

    @java.lang.SuppressWarnings("all")
    public void setBankName(final String bankName) {
        this.bankName = bankName;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsDefault(final Boolean isDefault) {
        this.isDefault = isDefault;
    }
}
