// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "seller_stores")
public class SellerStore extends BaseEntity {
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "seller_id", nullable = false, unique = true)
    private User seller;
    @Column(nullable = false)
    private String storeName;
    private String storeSlug;
    private String logoUrl;
    private String bannerUrl;
    @Column(columnDefinition = "TEXT")
    private String description;
    private String address;
    private String contactPhone;
    private String contactEmail;
    @Column(columnDefinition = "TEXT")
    private String returnPolicy;
    @Column(columnDefinition = "TEXT")
    private String shippingPolicy;
    private String status = "PENDING";
    private Boolean documentsVerified = false;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    public User getSeller() {
        return this.seller;
    }

    @java.lang.SuppressWarnings("all")
    public String getStoreName() {
        return this.storeName;
    }

    @java.lang.SuppressWarnings("all")
    public String getStoreSlug() {
        return this.storeSlug;
    }

    @java.lang.SuppressWarnings("all")
    public String getLogoUrl() {
        return this.logoUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getBannerUrl() {
        return this.bannerUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getContactPhone() {
        return this.contactPhone;
    }

    @java.lang.SuppressWarnings("all")
    public String getContactEmail() {
        return this.contactEmail;
    }

    @java.lang.SuppressWarnings("all")
    public String getReturnPolicy() {
        return this.returnPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public String getShippingPolicy() {
        return this.shippingPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getDocumentsVerified() {
        return this.documentsVerified;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setSeller(final User seller) {
        this.seller = seller;
    }

    @java.lang.SuppressWarnings("all")
    public void setStoreName(final String storeName) {
        this.storeName = storeName;
    }

    @java.lang.SuppressWarnings("all")
    public void setStoreSlug(final String storeSlug) {
        this.storeSlug = storeSlug;
    }

    @java.lang.SuppressWarnings("all")
    public void setLogoUrl(final String logoUrl) {
        this.logoUrl = logoUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setBannerUrl(final String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setContactPhone(final String contactPhone) {
        this.contactPhone = contactPhone;
    }

    @java.lang.SuppressWarnings("all")
    public void setContactEmail(final String contactEmail) {
        this.contactEmail = contactEmail;
    }

    @java.lang.SuppressWarnings("all")
    public void setReturnPolicy(final String returnPolicy) {
        this.returnPolicy = returnPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public void setShippingPolicy(final String shippingPolicy) {
        this.shippingPolicy = shippingPolicy;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setDocumentsVerified(final Boolean documentsVerified) {
        this.documentsVerified = documentsVerified;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
