// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

@Entity
@Table(name = "shipping_zones")
public class ShippingZone extends BaseEntity {
    private String name;
    @Column(columnDefinition = "TEXT")
    private String regions;
    private Double charge;
    private Double freeShippingThreshold;
    private Integer estimatedMinDays;
    private Integer estimatedMaxDays;
    private boolean active = true;
    private String courierPartner;
    private boolean codAvailable = true;

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegions() {
        return this.regions;
    }

    @java.lang.SuppressWarnings("all")
    public Double getCharge() {
        return this.charge;
    }

    @java.lang.SuppressWarnings("all")
    public Double getFreeShippingThreshold() {
        return this.freeShippingThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getEstimatedMinDays() {
        return this.estimatedMinDays;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getEstimatedMaxDays() {
        return this.estimatedMaxDays;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getCourierPartner() {
        return this.courierPartner;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isCodAvailable() {
        return this.codAvailable;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setRegions(final String regions) {
        this.regions = regions;
    }

    @java.lang.SuppressWarnings("all")
    public void setCharge(final Double charge) {
        this.charge = charge;
    }

    @java.lang.SuppressWarnings("all")
    public void setFreeShippingThreshold(final Double freeShippingThreshold) {
        this.freeShippingThreshold = freeShippingThreshold;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstimatedMinDays(final Integer estimatedMinDays) {
        this.estimatedMinDays = estimatedMinDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstimatedMaxDays(final Integer estimatedMaxDays) {
        this.estimatedMaxDays = estimatedMaxDays;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourierPartner(final String courierPartner) {
        this.courierPartner = courierPartner;
    }

    @java.lang.SuppressWarnings("all")
    public void setCodAvailable(final boolean codAvailable) {
        this.codAvailable = codAvailable;
    }
}
