// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "users")
@JsonIgnoreProperties({"refreshToken"})
public class User extends BaseEntity {
    private String fullName;
    private String username;
    @Column(unique = true, nullable = false)
    private String email;
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String phone;
    private String address;
    private String profilePicture;

    /**
     * The customer's PAN. Optional, and only meaningful for a business buyer.
     *
     * A registered buyer's PAN is already inside their GSTIN at characters 3-12, so this is not
     * a second source of truth - GstComplianceUtil.panMatchesGstin checks the two agree. It
     * exists for buyers who have a PAN but no GST registration, where returns and TCS reporting
     * still need to identify them.
     */
    @Column(name = "pan_number", length = 10)
    private String panNumber;

    /**
     * Enrolment number under Notification 34/2023, effective 01-10-2023.
     *
     * Lets a person supplying goods intra-state through an e-commerce operator trade without
     * full GST registration while under the threshold. It is an alternative to a GSTIN, not an
     * addition, so anything reading one has to accept the other.
     */
    @Column(name = "enrolment_number", length = 20)
    private String enrolmentNumber;
    @Column(nullable = false)
    private String status = "ACTIVE";
    @Enumerated(EnumType.STRING)
    private Role role = Role.CUSTOMER;
    private boolean active = true;
    @Column(length = 512)
    private String refreshToken;
    private Boolean mfaEnabled = false;
    private java.time.LocalDateTime lastLoginAt;
    private Integer failedLoginAttempts = 0;

    /**
     * When a lockout from failed logins stops applying.
     *
     * Without this the counter only ever reset on a successful login - which a locked-out
     * account cannot reach - so five wrong attempts locked someone out permanently while the
     * message told them to try again later. Waiting did nothing, and the only ways back were a
     * password reset or an admin.
     *
     * Null means not locked. A time in the past means the lockout has served its purpose and
     * the next attempt starts fresh.
     */
    private java.time.LocalDateTime lockedUntil;

    private Boolean mustResetPassword = false;
    private Integer tokenVersion = 0;
    private Long suspendedBy;
    private java.time.LocalDateTime suspendedAt;
    /** Why the account was stopped. Shown to the person it happened to, so it is written for them. */
    @Column(length = 500)
    private String suspensionReason;
    private String mfaSecret;
    private String mfaMethod = "TOTP";
    private java.time.LocalDateTime passwordChangedAt;
    private java.time.LocalDateTime passwordExpiresAt;
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private List<Address> addresses = new ArrayList<>();
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private List<Order> orders = new ArrayList<>();
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private Cart cart;

    /** Clears the refresh token and bumps the token version so previously issued access tokens stop passing JwtFilter's version check. */
    public void invalidateSessions() {
        this.refreshToken = null;
        this.tokenVersion = (this.tokenVersion == null ? 0 : this.tokenVersion) + 1;
    }

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getProfilePicture() {
        return this.profilePicture;
    }

    public String getPanNumber() {
        return this.panNumber;
    }

    public void setPanNumber(final String panNumber) {
        this.panNumber = panNumber;
    }

    public String getEnrolmentNumber() {
        return this.enrolmentNumber;
    }

    public void setEnrolmentNumber(final String enrolmentNumber) {
        this.enrolmentNumber = enrolmentNumber;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Role getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getRefreshToken() {
        return this.refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getMfaEnabled() {
        return this.mfaEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getFailedLoginAttempts() {
        return this.failedLoginAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getMustResetPassword() {
        return this.mustResetPassword;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTokenVersion() {
        return this.tokenVersion;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSuspendedBy() {
        return this.suspendedBy;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getSuspendedAt() {
        return this.suspendedAt;
    }

    @java.lang.SuppressWarnings("all")
    public String getMfaSecret() {
        return this.mfaSecret;
    }

    @java.lang.SuppressWarnings("all")
    public String getMfaMethod() {
        return this.mfaMethod;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getPasswordChangedAt() {
        return this.passwordChangedAt;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getPasswordExpiresAt() {
        return this.passwordExpiresAt;
    }

    @java.lang.SuppressWarnings("all")
    public List<Address> getAddresses() {
        return this.addresses;
    }

    @java.lang.SuppressWarnings("all")
    public List<Order> getOrders() {
        return this.orders;
    }

    @java.lang.SuppressWarnings("all")
    public Cart getCart() {
        return this.cart;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfilePicture(final String profilePicture) {
        this.profilePicture = profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final Role role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setMfaEnabled(final Boolean mfaEnabled) {
        this.mfaEnabled = mfaEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginAt(final java.time.LocalDateTime lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getLockedUntil() {
        return this.lockedUntil;
    }

    public void setLockedUntil(final java.time.LocalDateTime lockedUntil) {
        this.lockedUntil = lockedUntil;
    }

    public void setFailedLoginAttempts(final Integer failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public void setMustResetPassword(final Boolean mustResetPassword) {
        this.mustResetPassword = mustResetPassword;
    }

    @java.lang.SuppressWarnings("all")
    public String getSuspensionReason() {
        return this.suspensionReason;
    }

    public void setSuspensionReason(final String suspensionReason) {
        this.suspensionReason = suspensionReason;
    }

    public void setTokenVersion(final Integer tokenVersion) {
        this.tokenVersion = tokenVersion;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuspendedBy(final Long suspendedBy) {
        this.suspendedBy = suspendedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuspendedAt(final java.time.LocalDateTime suspendedAt) {
        this.suspendedAt = suspendedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setMfaSecret(final String mfaSecret) {
        this.mfaSecret = mfaSecret;
    }

    @java.lang.SuppressWarnings("all")
    public void setMfaMethod(final String mfaMethod) {
        this.mfaMethod = mfaMethod;
    }

    @java.lang.SuppressWarnings("all")
    public void setPasswordChangedAt(final java.time.LocalDateTime passwordChangedAt) {
        this.passwordChangedAt = passwordChangedAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setPasswordExpiresAt(final java.time.LocalDateTime passwordExpiresAt) {
        this.passwordExpiresAt = passwordExpiresAt;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setAddresses(final List<Address> addresses) {
        this.addresses = addresses;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setOrders(final List<Order> orders) {
        this.orders = orders;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setCart(final Cart cart) {
        this.cart = cart;
    }
}
