// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "users")
@JsonIgnoreProperties({"refreshToken"})
public class User extends BaseEntity {
    private String fullName;
    private String username;
    @Column(unique = true, nullable = false)
    private String email;
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;
    private String phone;
    private String address;
    private String profilePicture;
    @Column(nullable = false)
    private String status = "ACTIVE";
    @Enumerated(EnumType.STRING)
    private Role role = Role.CUSTOMER;
    private boolean active = true;
    @Column(length = 512)
    private String refreshToken;
    private Boolean mfaEnabled = false;
    private java.time.LocalDateTime lastLoginAt;
    private Integer failedLoginAttempts = 0;
    private Boolean mustResetPassword = false;
    private Integer tokenVersion = 0;
    private Long suspendedBy;
    private java.time.LocalDateTime suspendedAt;
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private List<Address> addresses = new ArrayList<>();
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private List<Order> orders = new ArrayList<>();
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JsonIgnoreProperties("user")
    private Cart cart;

    /** Clears the refresh token and bumps the token version so previously issued access tokens stop passing JwtFilter's version check. */
    public void invalidateSessions() {
        this.refreshToken = null;
        this.tokenVersion = (this.tokenVersion == null ? 0 : this.tokenVersion) + 1;
    }

    @java.lang.SuppressWarnings("all")
    public String getFullName() {
        return this.fullName;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getProfilePicture() {
        return this.profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public Role getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    public String getRefreshToken() {
        return this.refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getMfaEnabled() {
        return this.mfaEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getLastLoginAt() {
        return this.lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getFailedLoginAttempts() {
        return this.failedLoginAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getMustResetPassword() {
        return this.mustResetPassword;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTokenVersion() {
        return this.tokenVersion;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSuspendedBy() {
        return this.suspendedBy;
    }

    @java.lang.SuppressWarnings("all")
    public java.time.LocalDateTime getSuspendedAt() {
        return this.suspendedAt;
    }

    @java.lang.SuppressWarnings("all")
    public List<Address> getAddresses() {
        return this.addresses;
    }

    @java.lang.SuppressWarnings("all")
    public List<Order> getOrders() {
        return this.orders;
    }

    @java.lang.SuppressWarnings("all")
    public Cart getCart() {
        return this.cart;
    }

    @java.lang.SuppressWarnings("all")
    public void setFullName(final String fullName) {
        this.fullName = fullName;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setProfilePicture(final String profilePicture) {
        this.profilePicture = profilePicture;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final Role role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setMfaEnabled(final Boolean mfaEnabled) {
        this.mfaEnabled = mfaEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginAt(final java.time.LocalDateTime lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setFailedLoginAttempts(final Integer failedLoginAttempts) {
        this.failedLoginAttempts = failedLoginAttempts;
    }

    @java.lang.SuppressWarnings("all")
    public void setMustResetPassword(final Boolean mustResetPassword) {
        this.mustResetPassword = mustResetPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setTokenVersion(final Integer tokenVersion) {
        this.tokenVersion = tokenVersion;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuspendedBy(final Long suspendedBy) {
        this.suspendedBy = suspendedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setSuspendedAt(final java.time.LocalDateTime suspendedAt) {
        this.suspendedAt = suspendedAt;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setAddresses(final List<Address> addresses) {
        this.addresses = addresses;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setOrders(final List<Order> orders) {
        this.orders = orders;
    }

    @JsonIgnoreProperties("user")
    @java.lang.SuppressWarnings("all")
    public void setCart(final Cart cart) {
        this.cart = cart;
    }
}
