// Generated by delombok at Thu Jul 23 01:07:26 IST 2026
package com.cauverystore.entities;

import jakarta.persistence.*;

@Entity
@Table(name = "user_preferences")
public class UserPreferences extends BaseEntity {
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private User user;
    private String preferredCategories;
    private String preferredBrands;
    private Boolean emailNotifications = true;
    private Boolean smsNotifications = true;
    private Boolean pushNotifications = true;
    private Boolean twoFactorEnabled = false;
    private Boolean gdprConsent = false;
    private Boolean codPreference = true;
    @Column(columnDefinition = "TEXT")
    private String subscriptions;

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferredCategories() {
        return this.preferredCategories;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferredBrands() {
        return this.preferredBrands;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getEmailNotifications() {
        return this.emailNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getSmsNotifications() {
        return this.smsNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getPushNotifications() {
        return this.pushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getTwoFactorEnabled() {
        return this.twoFactorEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getGdprConsent() {
        return this.gdprConsent;
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getCodPreference() {
        return this.codPreference;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubscriptions() {
        return this.subscriptions;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferredCategories(final String preferredCategories) {
        this.preferredCategories = preferredCategories;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferredBrands(final String preferredBrands) {
        this.preferredBrands = preferredBrands;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmailNotifications(final Boolean emailNotifications) {
        this.emailNotifications = emailNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setSmsNotifications(final Boolean smsNotifications) {
        this.smsNotifications = smsNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setPushNotifications(final Boolean pushNotifications) {
        this.pushNotifications = pushNotifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setTwoFactorEnabled(final Boolean twoFactorEnabled) {
        this.twoFactorEnabled = twoFactorEnabled;
    }

    @java.lang.SuppressWarnings("all")
    public void setGdprConsent(final Boolean gdprConsent) {
        this.gdprConsent = gdprConsent;
    }

    @java.lang.SuppressWarnings("all")
    public void setCodPreference(final Boolean codPreference) {
        this.codPreference = codPreference;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubscriptions(final String subscriptions) {
        this.subscriptions = subscriptions;
    }
}
