// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

import java.util.List;
import java.util.Map;

public class AdminDashboardResponse {
    private long totalOrders;
    private double totalRevenue;
    private long totalProducts;
    private long totalUsers;
    private long pendingOrders;
    private long shippedOrders;
    private long deliveredOrders;
    private long cancelledOrders;
    private double refundAmount;
    private long refundCount;
    private List<Map<String, Object>> recentOrders;
    private List<Map<String, Object>> topProducts;
    private Map<String, Long> ordersByStatus;

    @java.lang.SuppressWarnings("all")
    public long getTotalOrders() {
        return this.totalOrders;
    }

    @java.lang.SuppressWarnings("all")
    public double getTotalRevenue() {
        return this.totalRevenue;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalProducts() {
        return this.totalProducts;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalUsers() {
        return this.totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public long getPendingOrders() {
        return this.pendingOrders;
    }

    @java.lang.SuppressWarnings("all")
    public long getShippedOrders() {
        return this.shippedOrders;
    }

    @java.lang.SuppressWarnings("all")
    public long getDeliveredOrders() {
        return this.deliveredOrders;
    }

    @java.lang.SuppressWarnings("all")
    public long getCancelledOrders() {
        return this.cancelledOrders;
    }

    @java.lang.SuppressWarnings("all")
    public double getRefundAmount() {
        return this.refundAmount;
    }

    @java.lang.SuppressWarnings("all")
    public long getRefundCount() {
        return this.refundCount;
    }

    @java.lang.SuppressWarnings("all")
    public List<Map<String, Object>> getRecentOrders() {
        return this.recentOrders;
    }

    @java.lang.SuppressWarnings("all")
    public List<Map<String, Object>> getTopProducts() {
        return this.topProducts;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, Long> getOrdersByStatus() {
        return this.ordersByStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalOrders(final long totalOrders) {
        this.totalOrders = totalOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalRevenue(final double totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalProducts(final long totalProducts) {
        this.totalProducts = totalProducts;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalUsers(final long totalUsers) {
        this.totalUsers = totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setPendingOrders(final long pendingOrders) {
        this.pendingOrders = pendingOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setShippedOrders(final long shippedOrders) {
        this.shippedOrders = shippedOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveredOrders(final long deliveredOrders) {
        this.deliveredOrders = deliveredOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setCancelledOrders(final long cancelledOrders) {
        this.cancelledOrders = cancelledOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefundAmount(final double refundAmount) {
        this.refundAmount = refundAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefundCount(final long refundCount) {
        this.refundCount = refundCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setRecentOrders(final List<Map<String, Object>> recentOrders) {
        this.recentOrders = recentOrders;
    }

    @java.lang.SuppressWarnings("all")
    public void setTopProducts(final List<Map<String, Object>> topProducts) {
        this.topProducts = topProducts;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrdersByStatus(final Map<String, Long> ordersByStatus) {
        this.ordersByStatus = ordersByStatus;
    }
}
