// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

import java.util.List;
import java.util.Map;

public class InvoiceResponse {
    private String orderId;
    private String customerName;
    private String customerEmail;
    private String phone;
    private String address;
    private String orderDate;
    private String status;
    private double subtotal;
    private double tax;
    private double deliveryCharge;
    private double totalAmount;
    private String paymentMethod;
    private List<Map<String, Object>> items;

    @java.lang.SuppressWarnings("all")
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCustomerName() {
        return this.customerName;
    }

    @java.lang.SuppressWarnings("all")
    public String getCustomerEmail() {
        return this.customerEmail;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getAddress() {
        return this.address;
    }

    @java.lang.SuppressWarnings("all")
    public String getOrderDate() {
        return this.orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public double getSubtotal() {
        return this.subtotal;
    }

    @java.lang.SuppressWarnings("all")
    public double getTax() {
        return this.tax;
    }

    @java.lang.SuppressWarnings("all")
    public double getDeliveryCharge() {
        return this.deliveryCharge;
    }

    @java.lang.SuppressWarnings("all")
    public double getTotalAmount() {
        return this.totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    public List<Map<String, Object>> getItems() {
        return this.items;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCustomerName(final String customerName) {
        this.customerName = customerName;
    }

    @java.lang.SuppressWarnings("all")
    public void setCustomerEmail(final String customerEmail) {
        this.customerEmail = customerEmail;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setAddress(final String address) {
        this.address = address;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderDate(final String orderDate) {
        this.orderDate = orderDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubtotal(final double subtotal) {
        this.subtotal = subtotal;
    }

    @java.lang.SuppressWarnings("all")
    public void setTax(final double tax) {
        this.tax = tax;
    }

    @java.lang.SuppressWarnings("all")
    public void setDeliveryCharge(final double deliveryCharge) {
        this.deliveryCharge = deliveryCharge;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalAmount(final double totalAmount) {
        this.totalAmount = totalAmount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPaymentMethod(final String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @java.lang.SuppressWarnings("all")
    public void setItems(final List<Map<String, Object>> items) {
        this.items = items;
    }
}
