// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

import java.util.List;
import java.util.Map;

public class OrderTimelineResponse {
    private String orderId;
    private String currentStatus;
    private List<Map<String, Object>> events;

    @java.lang.SuppressWarnings("all")
    public String getOrderId() {
        return this.orderId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrentStatus() {
        return this.currentStatus;
    }

    @java.lang.SuppressWarnings("all")
    public List<Map<String, Object>> getEvents() {
        return this.events;
    }

    @java.lang.SuppressWarnings("all")
    public void setOrderId(final String orderId) {
        this.orderId = orderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentStatus(final String currentStatus) {
        this.currentStatus = currentStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setEvents(final List<Map<String, Object>> events) {
        this.events = events;
    }
}
