// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class PasswordResetRequest {
    @NotBlank(message = "Email is required")
    @Email(message = "Please provide a valid email address")
    private String email;
    @NotBlank(message = "OTP is required")
    private String otp;
    @NotBlank(message = "New password is required")
    @Size(min = 8, message = "Password must be at least 8 characters")
    private String newPassword;

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getOtp() {
        return this.otp;
    }

    @java.lang.SuppressWarnings("all")
    public String getNewPassword() {
        return this.newPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setOtp(final String otp) {
        this.otp = otp;
    }

    @java.lang.SuppressWarnings("all")
    public void setNewPassword(final String newPassword) {
        this.newPassword = newPassword;
    }
}
