// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

public class PasswordResetRequest {
    private String email;
    private String otp;
    private String newPassword;

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getOtp() {
        return this.otp;
    }

    @java.lang.SuppressWarnings("all")
    public String getNewPassword() {
        return this.newPassword;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setOtp(final String otp) {
        this.otp = otp;
    }

    @java.lang.SuppressWarnings("all")
    public void setNewPassword(final String newPassword) {
        this.newPassword = newPassword;
    }
}
