// Generated by delombok at Thu Jul 23 08:34:17 IST 2026
package com.cauverystore.dto;

public class RefreshTokenRequest {
    private String refreshToken;

    @java.lang.SuppressWarnings("all")
    public String getRefreshToken() {
        return this.refreshToken;
    }

    @java.lang.SuppressWarnings("all")
    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }
}
